[package]
name = "bonjou-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
toml = "0.8"
crossterm = "0.27"
ratatui = "0.26"
tui-textarea = "0.4.0"
